name: DataDash Table Sum

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Playwright
        run: |
          npm init -y
          npm install playwright
          npx playwright install --with-deps

      - name: Run script 23ds3000088@ds.study.iitm.ac.in
        run: node scrape.js
